
name: mboistat
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 3.0.2+52

environment:
 sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.13
  path_provider: ^2.0.9
  open_file: ^3.2.1
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_downloader: ^1.6.1
  permission_handler: ^11.1.0
  flutter_pdfview: ^1.2.7
  dio: ^4.0.0
  package_info: ^2.0.2
  cached_network_image: ^3.0.0
  flutter_file_downloader: ^1.2.0
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/web/
    # - assets/icons/MboistatLogo.png
    # - assets/icons/ekonomi.png
    # - assets/icons/ipm.png
    # - assets/icons/kemiskinan.png
    # - assets/icons/kependudukan.png
    # - assets/icons/kesejahteraan.png
    # - assets/icons/ketenagakerjaan.png
    # - assets/icons/pertanian.png
    # - assets/icons/faq.png
    # - assets/icons/telephone.png
    # - assets/images/Rectangle8.png
    # - assets/images/gambar2.png
    # - assets/images/gambar3.png
    # - assets/images/pic1.jpeg

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Mbois-stat Logo_Fix Putih.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"