
name: mboistats
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 3.2.6+66

environment:
 sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_settings: ^5.1.1
  cached_network_image: ^3.0.0
  carousel_slider: ^5.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  fluttertoast: ^8.2.4
  flutter_downloader: ^1.6.1
  file_picker: ^8.0.0+1
  flutter_file_downloader: ^2.0.0
  http: ^1.2.0
  open_file: ^3.2.1
  open_settings: ^2.0.2
  package_info: ^2.0.2
  path_provider: ^2.0.11
  permission_handler: 10.4.5
  saf: ^1.0.3+4
  syncfusion_flutter_pdfviewer: ^28.1.41
  toast: ^0.3.0
  url_launcher: ^6.0.13
  webview_flutter: ^4.7.0
  webview_flutter_plus: ^0.4.4
package_info: ^2.0.3

 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/web/
    # - assets/icons/mboistatsLogo.png
    # - assets/icons/ekonomi.png
    # - assets/icons/ipm.png
    # - assets/icons/kemiskinan.png
    # - assets/icons/kependudukan.png
    # - assets/icons/kesejahteraan.png
    # - assets/icons/ketenagakerjaan.png
    # - assets/icons/pertanian.png
    # - assets/icons/faq.png
    # - assets/icons/telephone.png
    # - assets/images/Rectangle8.png
    # - assets/images/gambar2.png
    # - assets/images/gambar3.png
    # - assets/images/pic1.jpeg

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Mbois-stat Logo_Fix Putih.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"